name: mi-app-web
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - Flask==2.2.5
    - Werkzeug==2.2.3
    - Jinja2==3.1.2
    - MarkupSafe==2.1.1
    - itsdangerous==2.1.2
    - click==8.1.3
    - blinker==1.6.2
    - gunicorn==20.1.0
    - requests==2.28.2
    - beautifulsoup4==4.11.2
    - urllib3==1.26.15
    - Flask-WTF==1.0.1
    - WTForms==3.0.1
    - Flask-SQLAlchemy==2.5.1
    - psutil==5.9.4
    - cryptography==39.0.2
    - lxml==4.9.1
    - html5lib==1.1
