services:
  - type: web
    name: mi-app-web
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements_ultra_estable.txt
    startCommand: |
      gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
