services:
  - type: web
    name: mi-app-web
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PIP_NO_CACHE_DIR
        value: "1"