services:
  - type: web
    name: sistema-facturacion
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p uploads/capturas
      chmod 777 uploads/capturas
    startCommand: >-
      bash -lc '
      set -e
      export APP_DIR=/opt/render/project/src
      mkdir -p "$APP_DIR/storage"
      cd "$APP_DIR"
      for d in uploads uploads/capturas facturas_pdf facturas_json cotizaciones_pdf cotizaciones_json reportes_clientes reportes_cuentas reportes_facturas reportes_generales reportes_pagos historial_clientes logs; do
        mkdir -p "storage/$d"
        # Si existe un directorio real en el repo y no es symlink
        if [ -d "$d" ] && [ ! -L "$d" ]; then
          # Si el destino en storage está vacío pero el repo tiene datos, migrarlos
          if [ -z "$(ls -A storage/$d 2>/dev/null)" ] && [ -n "$(ls -A $d 2>/dev/null)" ]; then
            cp -a "$d/." "storage/$d/"
          fi
          rm -rf "$d"
        fi
        ln -sfn "storage/$d" "$d"
      done
      exec gunicorn app:app --workers 2 --threads 2 --timeout 180 --bind 0.0.0.0:$PORT
      '
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        sync: false
    healthCheckPath: /healthz
    autoDeploy: true 
    disk:
      name: data
      mountPath: /opt/render/project/src/storage
      sizeGB: 2